### ISSUE TITLE
This is a real emulator

### ISSUE THREAD

**Issue by dogtopus** [pcsx4/GS_plugin#1]
Thank you

**Comment by dogtopus** [comment]
By the way PS4 uses AMD GCN, not GS

**Comment by dogtopus** [comment]
![screenshot from 2018-05-25 03-03-38](https://user-images.githubusercontent.com/3405234/40528720-4d4c7264-5fc8-11e8-904b-de14e4d0f7d8.png)
#FAIL :p

**Comment by dogtopus** [comment]
Feel free to change anything to make this look legit, or figure out how to delete it. I already archived it on wayback machine anyway😜

**Comment by SimonNitzsche** [comment]
Thanks for advertising Orbital. Finally a real one.
